global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'booking-rush'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['APP_PRIVATE_IP:9090']  # management port (terraform apply 후 실제 IP로 교체)
